stages:
  - build
  - test
  - deploy

# Hidden job for readability
.on_project_branch:
  rules:
    # only work on branch 'project'
    - if: $CI_COMMIT_BRANCH == "project"

# Build
build-job:
  extends: .on_project_branch
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker compose build
  artifacts:
    paths:
      - docker-compose.yaml

# Run tests
test-job:
  extends: .on_project_branch
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker compose up -d
    # - docker-compose run tests
  after_script:
    - docker compose down
  dependencies:
    - build

# Deploy
deploy-job:
  extends: .on_project_branch
  stage: deploy
  services:
    - docker:dind
  script:
    - docker compose up -d