stages:
  - build
  - test
  - deploy

# Hidden job for readability
.on_project_branch:
  rules:
    # only work on branch 'project'
    - if: $CI_COMMIT_BRANCH == "project"

# Build
build-job:
  extends: .on_project_branch
  stage: build
  script:
    - echo "Building services"
    - docker compose build

# Run tests
test-job:
  extends: .on_project_branch
  stage: test
  script:
    - echo "Running tests"
    #- docker compose run --rm service1 npm test

# Deploy
deploy-job:
  extends: .on_project_branch
  stage: deploy
  script:
    - echo "Deploying services"
    - docker compose up -d