stages:
  - build
  - test
  - deploy

# Hidden job for readability
.on_project_branch:
  rules:
    # only work on branch 'project'
    - if: $CI_COMMIT_BRANCH == "project"

# Build
build-job:
  extends: .on_project_branch
  stage: build
  script:
    - docker compose build
  artifacts:
    paths:
      - docker-compose.yaml

# Run tests
test-job:
  extends: .on_project_branch
  stage: test
  script:
    - docker compose build tests
    - docker compose run --rm tests npm test
  after_script:
    - docker compose down
  dependencies:
    - build-job

# Deploy
deploy-job:
  extends: .on_project_branch
  stage: deploy
  script:
    - docker compose up -d