services:
  service1:
    build: ./service1
    deploy:
      replicas: 3
    networks:
      - loadbalancing
    depends_on:
      - service2

  service2:
    build: ./service2
    networks:
      - loadbalancing

  nginx:
    build: ./nginx
    ports:
      - "8198:80"
    networks:
      - loadbalancing
    depends_on:
      - state-manager

  state-manager:
    build: ./state-manager
    ports:
      - "8197:8197"
    networks:
      - loadbalancing
    depends_on:
      - service1

  tests:
    build: ./tests
    networks:
      - loadbalancing
    depends_on:
      - state-manager
    profiles:
      - test

networks:
  loadbalancing:
    driver: bridge