services:
  service1:
    build: ./service1
    # deploy:
    #   replicas: 3
    networks:
      - loadbalancing
    depends_on:
      - service2

  service2:
    build: ./service2
    networks:
      - loadbalancing

  nginx:
    build: ./nginx
    ports:
      - "8198:80"
    networks:
      - loadbalancing
    depends_on:
      - service1
      - service2

networks:
  loadbalancing:
    driver: bridge